# 设备与内存配置（设备描述与 memory（除 boot_pc）移动到此处）
[memory]
memory_base = 0x8000_0000
memory_size = 128

[[devices]]
name = "uart0"
type = "uart"
base = 0x1000_0000
size = 0x100
enabled = true

[[devices]]
name = "timer0"
type = "timer"
base = 0x1000_0100
size = 0x100
enabled = true
